language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python demo.py


deploy:
  provider: pypi
  user: jinsihou19
  password: $password
  on:
    python: 3.6
    tags: true
    branch: master